---
title: 'Milestone #2'
author: "Andy Price"
date: "9/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Diego Martinez's project, "Aging Curves Affect On Major League Baseball," works well because it uses visualizations to illustrate a concept that the reader implicitly understands on a general level but has trouble quantifying specifically. For example, it helped me understand that the phrase "aging curve" is used literally in baseball, even though I would have assumed aging decline is more linear. Seeing the shape of those declines (as opposed to a datatable that simply expressed player production by year) allowed me to intuitively grasp the shape of decline. The cons of a project like this, however, is that Diego had to rely on data from public databases that didn't include all the variables that one would want for this project. For example, it's noted that "the dataset did not split players into their specific outfield positons"; the limitations provided by the underlying dataset limit the scope of the project.

The benefits of the group project on blocking groups at Harvard are especially apparent when compared to a project like the one on MLB's aging curve, which relied on a limited public dataset: the group behind this project was able to gather whatever data it found interesting, without external constraints, because it was directly collecting data through a survey. The massive data collection effort, which succeeded in mostly overcoming the obstacles of an only one-half response rate, is the real feat of the project; I had trouble, though, understanding parts of their findings because I didn't know what to compare them to. When examining the racial and gender breakdowns of the houses, I didn't know what to compare them to other than those of different houses; I would have liked to see the likelihood of those breakdowns given a random distribution of blocking groups. Essentially, my biggest questions are of the variety of: how would a random distributing of blocking groups lead to such gender parity in every house. Is the college controlling for factors to simulate randomness? Some sort of final right-up would be helpful to cap off the truly interesting project. Additionally, a drawback of a project like this that works with sensitive personal data is that it requires the dataset not be published, making it impossible for a curious reader to reproduce their findings and explore more.